### ISSUE TITLE
i am seeing this type of issue while i try to run pybelt.py

### ISSUE THREAD

**Issue by Najam-ul-islam** [Ekultek/Pybelt#6] opened 2017-05-18 15:29 UTC
[11:27:50 INFO] Checking program integrity..
Traceback (most recent call last):
  File "pybelt.py", line 85, in <module>
    integrity_check()
  File "/home/najam/Pybelt/lib/core/settings.py", line 294, in integrity_check
    if open("{}\\docs\\checksum.md5".format(PATH)).read() == urllib2.urlopen(url).read():
IOError: [Errno 2] No such file or directory: '/home/najam/Pybelt\\docs\\checksum.md5'

**Comment by Ekultek** [comment] 2017-05-18 15:34
What OS are you using?

**Comment by psychomad** [comment] 2017-05-18 17:47
Same for me,
im using Debian 8

**Comment by Ekultek** [comment] 2017-05-18 17:51
I know what the problem is, give me some time. It was built on Windows so the paths are wrong

**Comment by psychomad** [comment] 2017-05-18 18:05
No prob, just gave my voice too :D

**Comment by Ekultek** [comment] 2017-05-18 18:08
Fixed via c677e19

**Comment by psychomad** [comment] 2017-05-18 18:14
Thanks a lot!

**Comment by Najam-ul-islam** [comment] 2017-05-19 04:55
i am using kali linux which is Debian based

**Comment by Najam-ul-islam** [comment] 2017-05-19 11:18
still it does not works for me

**Comment by Ekultek** [comment] 2017-05-19 11:43
Did you clone the newest version?

**Comment by Ekultek** [comment] 2017-05-19 11:52
Fixed via 3b81775

**Comment by Najam-ul-islam** [comment] 2017-05-19 11:54
yah bro i cloned newest

**Comment by Ekultek** [comment] 2017-05-19 12:00
![working_pybelt](https://cloud.githubusercontent.com/assets/14183473/26246857/d1983d00-3c60-11e7-8b9b-36a50a654f98.PNG)


Parrot is Debian based like Kali, download newest version or clone it, and try again. I'll keep this open until you reply back

**Comment by Ekultek** [comment] 2017-05-20 22:57
24 hours no complaints, guessing it worked. Closing this down

**Closed as completed by Ekultek** 2017-05-20 22:57 UTC
Labels: OS specific
